### ISSUE TITLE
Error seeds

### ISSUE THREAD

**Issue by yuri25** [alimranahmed/Personal-Blog-Using-Laravel5#2]
yuran@REANIMATOR c:\OpenServer\domains\bbbb
$ php artisan migrate:refresh --seed
Migration table not found.
Migration table created successfully.
Migrated: 2014_09_01_014904_create_images_table
Migrated: 2014_10_11_015137_create_addresses_table
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_000001_create_readers_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2016_10_01_014152_create_categories_table
Migrated: 2016_10_01_014203_create_keywords_table
Migrated: 2016_10_01_014543_create_articles_table
Migrated: 2016_10_01_014930_create_comments_table
Migrated: 2016_10_01_014944_create_pages_table
Migrated: 2016_10_01_014952_create_assets_table
Migrated: 2016_10_01_015118_create_email_logs_table
Migrated: 2016_10_03_014544_create_article_image_table
Migrated: 2016_10_03_190244_create_article_keyword_table
Migrated: 2016_12_24_171919_entrust_setup_tables

  [BadMethodCallException]
  This cache store does not support tagging.

Tables "users", "role_user", "permission_role", "permissions" and some others - empty.  
Probably because of this error:
 [BadMethodCallException]
  This cache store does not support tagging.

**Comment by alimranahmed** [comment]
In your `.env` file change the `CACHE_DRIVER` to `array` like below: 

`CACHE_DRIVER=array`

**Comment by yuri25** [comment]
[BadMethodCallException]
 This cache store does not support tagging.
In my .env file I tried so:CACHE_DRIVER=array   
also try so: CACHE_DRIVER=file 
The error still persists:

$ php artisan migrate:refresh --seed
Migration table not found.
Migration table created successfully.
Migrated: 2014_09_01_014904_create_images_table
Migrated: 2014_10_11_015137_create_addresses_table
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_000001_create_readers_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2016_10_01_014152_create_categories_table
Migrated: 2016_10_01_014203_create_keywords_table
Migrated: 2016_10_01_014543_create_articles_table
Migrated: 2016_10_01_014930_create_comments_table
Migrated: 2016_10_01_014944_create_pages_table
Migrated: 2016_10_01_014952_create_assets_table
Migrated: 2016_10_01_015118_create_email_logs_table
Migrated: 2016_10_03_014544_create_article_image_table
Migrated: 2016_10_03_190244_create_article_keyword_table
Migrated: 2016_12_24_171919_entrust_setup_tables
Migrated: 2017_01_05_183023_create_jobs_table


  [BadMethodCallException]
  This cache store does not support tagging.
